title: How to install Node.js
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: install-nodejs-template    # the name of the repository when it is created for the learner
  repo: lab-starter-template    # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

# the type of action, full list at https://lab.github.com/docs/actions/
# some actions require additional options, those should appear below `type:`
# you can execute multiple actions in the `before` block
before:
- type: respond
  with: 01_first-response.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP
- title: Install nvm â€“ Node Version Manager
  description: This step explains how to install nvm, Node Version Manager. You use nvm to install multiple Node.js versions.
  event: issue_commented.created  # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
- title: Install Node.js using nvm
  description: Let's start installing Node.js versions using nvm.
  event: issue_commented.created  # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
- title: Introduce the most used nvm commands
  description: This step explains the most frequently used nvm commands.
  event: issue_commented.created  # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
- title: Tips for manageing multiple Node.js versions.
  description: Some important tips regarding Node.js version management are discussed in this step.
  event: issue_commented.created  # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
- title: Summary
  description: Course summary.
  event: issue_commented.created  # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions
